### ISSUE TITLE
Add Real Property Related docs

### ISSUE THREAD

**Issue by drpaudyal** [VA-ENTERPRISE-ARCHITECTURE/ADS-DATA-QUALITY#5]
Add Real Property Related docs

**Comment by drpaudyal** [comment]
@KaltunA

**Comment by KaltunA** [comment]
[DGC Real Property - Priority 1 Info Classes_2018.07.23_V6 MattchingAttNames.xlsx](https://github.com/VA-ENTERPRISE-ARCHITECTURE/ADS-DATA-QUALITY/files/3610451/DGC.Real.Property.-.Priority.1.Info.Classes_2018.07.23_V6.MattchingAttNames.xlsx)
